url: https://pinmike.github.io
baseurl: 

# Site settings
title: github.pinmike.io
email: mike@pinmike.io
description: "Pinmike's Github Pages, powered by Github and Jekyll."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mike Pinnell
  pic: 1
  position: Head of Development
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/pinmike
  - title: linkedin
    url: http://linkedin.com/in/mikepinnell
  - title: stack-overflow 
    url: http://stackoverflow.com/users/2685271/mike-pinnell
  - title: codewars
    url: https://www.codewars.com/users/Pinmike
  - title: codepen
    url: https://codepen.io/pinmike/
  - title: hackerrank
    url: https://www.hackerrank.com/pinmike
  - title: bitbucket
    url: https://bitbucket.org/pinmike/
  - title: twitter
    url: http://twitter.com/mikepinnell
  - title: facebook
    url: https://www.facebook.com/michael.pinnell

# Postal address (add as many lines as necessary)
address:
  - line: North Laine
  - line: Brighton, UK

# Build settings
markdown: kramdown
permalink: pretty