# Site settings
title: Pinmike's Github pages
email: mike@pinmike.io
description: Pinmike's Github pages
baseurl: 
url: http://github.pinmike.io

twitter_username: mikepinnell
github_username:  pinmike
linkedin_profile: mikepinnell

# Build settings
name: github.pinmike.io
markdown: redcarpet
pygments: true
