# Site wide configuration

title: github.pinmike.io
description:
logo: /images/MangaMike_120x120.jpg
teaser: # 400x250 px default teaser image used in image archive grid
locale: http://pinmike.github.io
url: 

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Mike Pinnell
  email: mike@pinmike.io
  twitter: mikepinnell
  linkedin: mikepinnell
  github: pinmike
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
